[package]
name = "forsith-decoding"
version = "0.1.0"
edition = "2024"
autotests = false

[dependencies]
forsith-shared = { path = "../forsith-shared" }
anyhow = "1.0.104"
const_for = "0.1.5"
derive_more = { version = "2.1.1", features = ["not", "index_mut", "index", "deref", "deref_mut"] }
forsith-proc = { path = "../forsith-proc" }
num_enum = "0.7.6"
thiserror = "2.0.18"

[features]
default = [
    # "png",
    # "jpeg",
    "xml"
]
image = []
png = ["image"]
jpeg = ["image"]
xml = []

[dev-dependencies]
serde_json = "1.0.150"
criterion = { version = "0.8", features = ["html_reports"] }

# [[test]]
# name = "png"
# path = "tests/png.rs"

# [[bench]]
# name = "png_decode"
# harness = false
