[package]
name = "forsith-decoding"
version = "0.1.0"
edition = "2024"
autotests = false

[dependencies]
forsith-shared = { path = "../forsith-shared" }
forsith-proc = { path = "../forsith-proc" }

[features]
default = [
    # "png",
    # "jpeg",
    "xml"
]
image = []
png = ["image"]
jpeg = ["image"]
xml = []

[dev-dependencies]
serde_json = "1.0.150"
criterion = { version = "0.8", features = ["html_reports"] }

# [[test]]
# name = "png"
# path = "tests/png.rs"

# [[bench]]
# name = "png_decode"
# harness = false
