name: Rust Vulkan Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Vulkan SDK dependencies
        run: sudo apt-get install -y libvulkan1 mesa-vulkan-drivers

      - name: Download Vulkan SDK setup script
        run: wget -qO vulkan_sdk.sh https://sdk.lunarg.com/sdk/download/latest/linux/vulkan-sdk.run

      - name: Make Vulkan SDK setup script executable
        run: chmod +x vulkan_sdk.sh

      - name: Install Vulkan SDK
        run: |
          ./vulkan_sdk.sh -- --accept-licenses --default-root
          export VULKAN_SDK=$HOME/VulkanSDK/$(ls $HOME/VulkanSDK | sort -V | tail -n 1)/x86_64
          echo "VULKAN_SDK=$VULKAN_SDK" >> $GITHUB_ENV
          echo "PATH=$VULKAN_SDK/bin:$PATH" >> $GITHUB_ENV
          echo "LD_LIBRARY_PATH=$VULKAN_SDK/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: clippy, rustfmt

      - name: Build project
        run: cargo build --release

      - name: Run tests
        run: |
          timeout 10 cargo test --release
