The exit code 8 from tar usually indicates an error in reading the tarball. It might be due to a corrupted download or an incorrect URL.

Let's ensure we get the correct URL and handle any potential issues during the download process. We will also add error handling for each step to get more informative error messages.

Here's the updated workflow:

yaml

name: Rust Vulkan Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Vulkan SDK dependencies
        run: sudo apt-get install -y libvulkan1 mesa-vulkan-drivers

      - name: Download Vulkan SDK
        run: |
          wget -O vulkan_sdk.tar.gz https://sdk.lunarg.com/sdk/download/latest/linux/vulkansdk-linux-x86_64.tar.gz
          if [ $? -ne 0 ]; then
            echo "Failed to download Vulkan SDK"
            exit 1
          fi

      - name: Extract Vulkan SDK
        run: |
          mkdir vulkan_sdk
          tar -xzf vulkan_sdk.tar.gz -C vulkan_sdk --strip-components=1
          if [ $? -ne 0 ]; then
            echo "Failed to extract Vulkan SDK"
            exit 1
          fi
          export VULKAN_SDK=$PWD/vulkan_sdk/x86_64
          echo "VULKAN_SDK=$VULKAN_SDK" >> $GITHUB_ENV
          echo "PATH=$VULKAN_SDK/bin:$PATH" >> $GITHUB_ENV
          echo "LD_LIBRARY_PATH=$VULKAN_SDK/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: clippy, rustfmt

      - name: Build project
        run: cargo build --release

      - name: Run tests
        run: |
          timeout 10 cargo test --release
