name: Rust Vulkan Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Vulkan SDK dependencies
        run: sudo apt-get install -y libvulkan1 mesa-vulkan-drivers

      - name: Download and extract Vulkan SDK
        run: |
          wget -qO vulkan_sdk.tar.gz https://sdk.lunarg.com/sdk/download/latest/linux/vulkansdk-linux-x86_64.tar.gz
          mkdir vulkan_sdk
          tar -xzf vulkan_sdk.tar.gz -C vulkan_sdk --strip-components=1
          export VULKAN_SDK=$PWD/vulkan_sdk/x86_64
          echo "VULKAN_SDK=$VULKAN_SDK" >> $GITHUB_ENV
          echo "PATH=$VULKAN_SDK/bin:$PATH" >> $GITHUB_ENV
          echo "LD_LIBRARY_PATH=$VULKAN_SDK/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: clippy, rustfmt

      - name: Build project
        run: cargo build --release

      - name: Run tests
        run: |
          timeout 10 cargo test --release
